    drop table if exists history CASCADE;

    drop table if exists role CASCADE;

    drop table if exists tb_category CASCADE;

    drop table if exists tb_user CASCADE;

   drop table if exists title CASCADE;

   drop table if exists user_role CASCADE;

    create table history (
       id bigint generated by default as identity,
        create_date timestamp,
        description varchar(255),
        title_id bigint,
        user_id bigint,
        primary key (id)
    );

    create table role (
       id bigint generated by default as identity,
        authorities varchar(255),
        primary key (id)
    );

    create table tb_category (
       id bigint generated by default as identity,
        activated integer,
        description varchar(255),
        primary key (id)
    );

    create table tb_user (
       id bigint generated by default as identity,
        activated integer,
        email varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table title (
       id bigint generated by default as identity,
        category_id bigint,
        create_date timestamp,
        description varchar(255),
        discount decimal(19,2),
        expiration_date timestamp,
        payment_date timestamp,
        situation integer,
        type integer,
        value decimal(19,2),
        primary key (id)
    );
    create table user_role (
       user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    alter table user_role
       add constraint FKa68196081fvovjhkek5m97n3y
       foreign key (role_id)
       references role;

    alter table user_role
       add constraint FK430om9qnxgilp5cvcbeyovi37
        foreign key (user_id)
        references tb_user;



INSERT INTO tb_category (activated, description) VALUES (1, 'Alimentação');
INSERT INTO tb_category (activated, description) VALUES (1, 'Autmovel');
INSERT INTO tb_category (activated, description) VALUES (1, 'Financiamento');

